# Generated by Django 4.0.6 on 2022-08-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Форма обучения')),
            ],
            options={
                'verbose_name': 'Форма обучения в ХТУ',
                'verbose_name_plural': 'Формы обучения в ХТУ',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность ХТУ',
                'verbose_name_plural': 'Специальности ХТУ',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=16, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=16, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('hostel', models.BooleanField(blank=True, default=False, verbose_name='Необходимость в общежитии')),
                ('benefits', models.CharField(blank=True, max_length=256, verbose_name='Льготы')),
                ('curs', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('group', models.CharField(blank=True, max_length=16, verbose_name='Группа')),
                ('prog', models.CharField(blank=True, max_length=512, verbose_name='Образовательная программа')),
                ('level', models.CharField(blank=True, max_length=256, verbose_name='Уровень обучения')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('education_form', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='applicant_db.educationform', verbose_name='Форма обучения')),
                ('specialization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='applicant_db.specialization', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Студент ХТУ',
                'verbose_name_plural': 'Студенты ХТУ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=16, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=16, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('education_doc', models.CharField(blank=True, max_length=256, verbose_name='Документ об образовании')),
                ('passport', models.CharField(blank=True, max_length=512, verbose_name='Номер паспорта')),
                ('ic', models.CharField(blank=True, max_length=64, verbose_name='Идентификационный код')),
                ('hostel', models.BooleanField(blank=True, default=False, verbose_name='Необходимость в общежитии')),
                ('benefits', models.CharField(blank=True, max_length=256, verbose_name='Льготы')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('education_form', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='applicant_db.educationform', verbose_name='Форма обучения')),
                ('specialization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='applicant_db.specialization', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Абитуриент ХТУ',
                'verbose_name_plural': 'Абитуриенты ХТУ',
                'ordering': ['-created'],
            },
        ),
    ]
