# Generated by Django 4.0.6 on 2022-08-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Уровень обучения')),
            ],
            options={
                'verbose_name': 'Уровень обучения в ХТУ',
                'verbose_name_plural': 'Уровни обучения в ХТУ',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='level_of_study',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='applicant_db.levelofstudy', verbose_name='Уровень обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='level_of_study',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='applicant_db.levelofstudy', verbose_name='Уровень обучения'),
            preserve_default=False,
        ),
    ]
